package enums;

public enum Ad_Unit {
    MEDIUM_RECTANGLE,
    RECTANGLE,
    LEADERBOARD,
    FULL_BANNER,
    SKYSCRAPER,
    WIDE_SKYSCRAPER,
    HALF_PAGE_AD,
    BUTTON_2,
    MICRO_BAR,
    XXL_BOX,
    CUSTOM_SITE_BANNER_SIZE
}
