package enums;

/**
 * Created by user8 on 18.10.2016.
 */
public enum Entity {
    PLACEMENT, CHANNEL, ZONE, SITE, BANNER, CAMPAIGN, ACTION, ADVERTISER, COUNTRY, PLACEMENT_SIZE, PLACEMENT_TYPE, OPERATING_SYSTEM, BROWSER, MOBILE_NETWORK, PLATFORM, REFERER

}
